---
title: "Likelihood ratio test for interaction term"
output:
  html_notebook:
    toc: true
    number_sections: true
    theme: readable
author: Nuo Xu
---

# Preprocessing

## Load libraries

```{r}
library(tidyverse)
library(org.Hs.eg.db)
```

## Load data

```{r}
symbols <- mapIds(
    org.Hs.eg.db,
    keys = keys(org.Hs.eg.db, "ENSEMBL"),
    column = c("SYMBOL"),
    keytype = "ENSEMBL"
)

gene_types <- mapIds(
    org.Hs.eg.db,
    keys = keys(org.Hs.eg.db, "ENSEMBL"),
    column = c("GENETYPE"),
    keytype = "ENSEMBL"
)
```

# Run DESeq2

```{r}
dds_wendy <- readRDS("proc/dds_wendy.rds")
design(dds_wendy) <- formula(~ condition + assay + condition:assay)
dds_wendy <- DESeq(dds_wendy, test = "LRT", reduced = ~ assay + condition)
res <- results(dds_wendy)
```

```{r}
res_lfcShrink <- dds_wendy %>%
    lfcShrink(coef="conditionPTEN_KO.assayInput", type="apeglm") %>%
    as.data.frame() %>%
    mutate(symbol = symbols[rownames(res)]) %>% 
    mutate(gene_type = gene_types[rownames(res)])
```

# Visualization

```{r}
res_lfcShrink %>%
    filter(padj < 0.1) %>%
    arrange(desc(abs(log2FoldChange))) %>%
    write.csv("test.csv")
```

```{r}
gene_types["ENSG00000204789"]
length(gene_types)
```

```{r}
plotCounts(dds_wendy, gene="ENSG00000204789", intgroup=c("assay", "condition"))
```