---
title: "May 10th"
output:
  html_notebook:
    toc: true
    number_sections: true
    theme: readable
author: Nuo Xu
---

# Preprocessing
```{r load-libraries}
library(tidyverse)
library(DESeq2)
library(ggplot2)
```

```{r load-data}
dds_wendy <- readRDS("proc/dds_wendy.rds")
interaction_results <- read.csv("results/interaction/raw_interaction_results.csv")
```

# Run DESeq2
```{r}
design(dds_wendy) <- formula(~ assay + condition + assay:condition)
dds_wendy <- DESeq(dds_wendy, test = "LRT", reduced = ~ assay + condition)
res <- results(dds_wendy)
```

# Visualization
```{r}
DESeq2::plotCounts(dds_wendy, "ENSG00000238795", intgroup = c("condition", "assay"))


res["ENSG00000238795", ]
```

Re-implement the `plotCounts` function using ggplot.
```{r}
plotCounts <- function(dds, interaction_results, ensembl_id) {
    cnts <- counts(dds, normalized = TRUE, replaced = FALSE)[ensembl_id, ]
    intgroup <- c("condition", "assay")
    gene_name <- interaction_results[interaction_results$X == ensembl_id, "symbol"]
    merge(colData(dds)[, intgroup], cnts, by = "row.names")
    colData(dds) %>%
        as.data.frame() %>%
        mutate(count = cnts) %>%
        ggplot(aes(x = condition, y = count, colour = assay)) +
        geom_jitter() +
        ggtitle(gene_name)
}

plotCounts(dds_wendy, interaction_results, "ENSG00000238795")
plotCounts(dds_wendy, interaction_results, "ENSG00000164199")

res["ENSG00000251322", ]

```