---
title: "Transcriptome and proteome correlation"
output:
  html_notebook:
    toc: true
    number_sections: true
    theme: readable
author: Nuo Xu
---
# Preprocessing

## Loading libraries

```{r}
library(dplyr)
library(readxl)
library(DESeq2)
library(biomaRt)
library(ggplot2)
```

## Loading mappings
```{r}
ensembl <- useMart("ensembl", dataset = "hsapiens_gene_ensembl")
attributes <- c("uniprotswissprot", "ensembl_gene_id")
mapping <- getBM(attributes = attributes, mart = ensembl)
```

## Loading data
```{r}
RA <- read.csv("data/Live_pq_3619_TMTMosaic.csv")
dds <- readRDS("proc/dds_wendy.rds")
txi <- readRDS("proc/txi_wendy.rds")
```

```{r}
transcriptome_TPM <- txi$abundance %>%
    as.data.frame() %>%
    dplyr::select(c("87_Input", "91_Input", "90_Input")) %>%
    rowMeans()

translatome_TPM <- txi$abundance %>%
    as.data.frame() %>%
    dplyr::select(c("87_IP", "90_IP", "91_IP")) %>%
    rowMeans()
```

## Data wrangling
```{r}
IP_res <- IP_res %>% 
    as.data.frame()
IP_res <- IP_res %>%
    mutate(ensembl_gene_id = rownames(.))

IP_only <- dds[, colData(dds)$assay == "IP"]
translatome <- counts(IP_only, normalized = TRUE)
translatome <- translatome[, colData(IP_only)$condition == "WT"] %>%
    rowMeans() %>% 
    data.frame(translatome = .) %>% 
    mutate(ensembl_gene_id = rownames(.))

Input_only <- dds[, colData(dds)$assay == "Input"]
transcriptome <- counts(Input_only, normalized = TRUE)
transcriptome <- transcriptome[, colData(Input_only)$condition == "WT"] %>%
    rowMeans() %>% 
    data.frame(transcriptome = .) %>% 
    mutate(ensembl_gene_id = rownames(.))

test <- data.frame(
ensembl_gene_id = rownames(translatome), 
x = translatome$translatome/transcriptome$transcriptome
)



mean_t30 <- RA %>% 
    mutate(mean_t30 = rowMeans(dplyr::select(., contains("t30")))) %>% 
    dplyr::select(c("UniprotID", "mean_t30")) %>% 
    left_join(mapping, by = c("UniprotID" = "uniprotswissprot")) %>% 
    left_join(translatome, by = c("ensembl_gene_id")) %>%
    left_join(transcriptome, by = c("ensembl_gene_id")) %>% 
    left_join(test, by = c("ensembl_gene_id")) %>%
    left_join(as_tibble(IP_res, rownames = "ensembl_gene_id")[, c("ensembl_gene_id", "log2FoldChange")], by = c("ensembl_gene_id")) %>% 
    rename(IP_FC = log2FoldChange) %>%
    left_join(as_tibble(Input_res, rownames = "ensembl_gene_id")[, c("ensembl_gene_id", "log2FoldChange")], by = c("ensembl_gene_id")) %>%
    rename(Input_FC = log2FoldChange) %>%
    mutate(translatome_TPM = translatome_TPM[match(ensembl_gene_id, names(translatome_TPM))]) %>% 
    mutate(transcriptome_TPM = transcriptome_TPM[match(ensembl_gene_id, names(transcriptome_TPM))])
```

# Plotting
```{r}
# proteome vs transcriptome
mean_t30 %>% 
    ggplot(aes(x = log10(translatome_TPM+1), y = log10(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    xlab("log10 (TPM + 1) for transcriptome") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()

mean_t30 %>% 
    ggplot(aes(x = log10(x), y = log10(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    xlab("log10 (TPM + 1) for transcriptome") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()    

# proteome vs translatome
mean_t30 %>% 
    ggplot(aes(x = log10(transcriptome_TPM+1), y = log10(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    xlab("log10 (TPM + 1) for translatome") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()

# proteome vs IP_FC
mean_t30 %>% 
    ggplot(aes(x = IP_FC, y = log10(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    xlab("log2FoldChange in IP") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()    

# proteome vs Input_FC
mean_t30 %>% 
    ggplot(aes(x = Input_FC, y = log10(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    xlab("log2FoldChange in Input") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()       

DESeq2_RE <- read.csv("results/interaction/shrink_interaction_results.csv")

mean_t30 %>% 
    left_join(DESeq2_RE, join_by(ensembl_gene_id == X)) %>% 
    ggplot(aes(x = log2FoldChange, y = log2(mean_t30+1))) + 
    geom_point(alpha = 0.2) + 
    geom_smooth(method = 'lm', se = FALSE) + 
    scale_x_continuous(limits = c(-1, 1)) +
    xlab("log2 RE between PTEN_KO and WT") +
    ylab("log10 (RA + 1) for protein expression") +
    stat_cor()
```





