---
title: "Comparing results from quantilile.normalizes"
output:
  html_notebook:
    toc: true
    number_sections: true
    theme: readable
author: Nuo Xu
---

# Preparation

## Loading libraries

```{r load-libraries, message=FALSE, warning=FALSE, echo=FALSE}
library(dplyr)
library(preprocessCore)
library(stringr)
```

```{r}
quantile_normalize <- function(df){
    df %>%
        data.matrix() %>%
        preprocessCore::normalize.quantiles() %>%
        as.data.frame()
}
get_results <- function(RE_normalized) {
    RE_KO <- RE[, str_detect(colnames(RE), "4_7|4_9|95_3")]
    RE_WT <- RE[, str_detect(colnames(RE), "87|90|91")]

    log2_RE_FC <- log(rowMeans(RE_KO, na.rm = TRUE) / rowMeans(RE_WT, na.rm = TRUE), 2)
    Z_score <- rowMeans(RE_KO, na.rm = TRUE) - rowMeans(RE_WT, na.rm = TRUE) / sqrt(apply(RE_KO, 1, sd, na.rm = TRUE)**2 + apply(RE_WT, 1, sd, na.rm = TRUE)**2)

    results <- data.frame(gene_id = names(log2_RE_FC), log2_RE_FC = log2_RE_FC, Z_score = Z_score)
    return(results)
}
```
```{r}
RE <- read.csv("results/RE_quant/linux_RE_unormalized.csv", row.names = 1)

RE_normalized <- quantile_normalize(RE)
results <- get_results(RE_normalized)
```

